# -*- coding: utf-8 -*-
import io
from datetime import datetime, time
import xlsxwriter

COLUMNS = [
    ('employee_code', 'Employee ID / الرقم الوظيفي', 18, 'text'),
    ('employee_name', 'Employee Name / اسم الموظف', 32, 'text'),
    ('company_name', 'Company / الشركة', 22, 'text'),
    ('department_name', 'Department / القسم', 22, 'text'),
    ('job_title', 'Job Position / المسمى الوظيفي', 22, 'text'),
    ('payrun_name', 'Pay Run / مسير الرواتب', 22, 'text'),
    ('period', 'Period / الفترة', 22, 'text'),
    ('hourly_wage', 'Hourly Wage / أجر الساعة', 18, 'currency'),
    ('hours_per_day', 'Daily Hours / ساعات اليوم', 16, 'number'),
    ('daily_rate', 'Daily Rate / تكلفة اليومية', 18, 'currency'),
    ('attendance_days', 'Attendance Days / أيام الدوام', 18, 'number'),
    ('attendance_hours', 'Attendance Hours / ساعات الدوام', 18, 'number'),
    ('monthly_cost', 'Total Cost / تكلفة الموظف', 22, 'cost'),
    ('line_amount', 'Payslip Attendance Amt / مبلغ الحضور', 22, 'currency'),
    ('payslip_net', 'Payslip Net / صافي الراتب', 18, 'currency'),
    ('payslip_status', 'Status / الحالة', 16, 'text'),
    ('notes', 'Notes / ملاحظات', 35, 'text'),
]

def build_cost_center_xlsx(rows, metadata):
    buffer = io.BytesIO()
    book = xlsxwriter.Workbook(
        buffer,
        {'in_memory': True, 'strings_to_formulas': False, 'strings_to_urls': False}
    )
    sheet = book.add_worksheet('Cost Center')
    sheet.hide_gridlines(2)
    sheet.set_landscape()
    sheet.set_paper(9)  # A4
    sheet.fit_to_pages(1, 0)
    sheet.set_zoom(90)

    # Styles
    title_fmt = book.add_format({
        'bold': True, 'font_size': 18, 'font_color': '#17365D', 'font_name': 'Segoe UI'
    })
    subtitle_fmt = book.add_format({
        'font_size': 11, 'font_color': '#4A5568', 'font_name': 'Segoe UI'
    })
    info_fmt = book.add_format({
        'font_size': 10, 'font_color': '#718096', 'font_name': 'Segoe UI'
    })

    # KPI Summary Card Styles
    kpi_box = {
        'border': 1, 'border_color': '#CBD5E1', 'valign': 'vcenter', 'align': 'center'
    }
    kpi_title_fmt = book.add_format(dict(kpi_box, bold=True, font_size=9, bg_color='#F1F5F9', font_color='#475569'))
    kpi_value_fmt = book.add_format(dict(kpi_box, bold=True, font_size=12, bg_color='#FFFFFF', font_color='#0F172A'))
    kpi_cost_fmt = book.add_format(dict(kpi_box, bold=True, font_size=13, bg_color='#ECFDF5', font_color='#065F46', num_format='#,##0.000'))

    header_fmt = book.add_format({
        'bold': True, 'bg_color': '#17365D', 'font_color': '#FFFFFF',
        'text_wrap': True, 'valign': 'vcenter', 'align': 'center',
        'border': 1, 'border_color': '#0F243E', 'font_name': 'Segoe UI', 'font_size': 10
    })

    base_cell = {
        'font_name': 'Segoe UI', 'font_size': 10, 'border': 1,
        'border_color': '#E2E8F0', 'valign': 'vcenter'
    }
    text_fmt = book.add_format(dict(base_cell, align='left', text_wrap=True))
    text_center_fmt = book.add_format(dict(base_cell, align='center'))
    num_fmt = book.add_format(dict(base_cell, align='right', num_format='#,##0.00'))
    curr_fmt = book.add_format(dict(base_cell, align='right', num_format='#,##0.000'))
    cost_fmt = book.add_format(dict(base_cell, bold=True, align='right', bg_color='#F8FAFC', font_color='#1E3A8A', num_format='#,##0.000'))

    total_fmt = book.add_format({
        'bold': True, 'bg_color': '#E8EEF5', 'font_color': '#0F172A',
        'font_name': 'Segoe UI', 'font_size': 10, 'border': 1,
        'border_color': '#CBD5E1', 'valign': 'vcenter', 'align': 'right',
        'num_format': '#,##0.000'
    })
    total_label_fmt = book.add_format({
        'bold': True, 'bg_color': '#E8EEF5', 'font_color': '#0F172A',
        'font_name': 'Segoe UI', 'font_size': 10, 'border': 1,
        'border_color': '#CBD5E1', 'valign': 'vcenter', 'align': 'center'
    })

    # Header section
    sheet.merge_range('A1:G1', 'EMPLOYEES COST CENTER REPORT | تقرير مركز تكلفة الموظفين', title_fmt)
    sheet.merge_range('A2:G2', f"Company: {metadata.get('company', '')}  |  Period: {metadata.get('period', '')}  |  Pay Run: {metadata.get('payrun', 'All')}", subtitle_fmt)
    sheet.merge_range('A3:G3', f"Generated by: {metadata.get('user', '')}  |  Date: {metadata.get('generated', '')}  |  Currency: {metadata.get('currency', 'JOD')}", info_fmt)

    # KPI Banner (Row 4 & 5)
    tot_emp = len(rows)
    tot_days = sum(r.get('attendance_days', 0.0) for r in rows)
    tot_hours = sum(r.get('attendance_hours', 0.0) for r in rows)
    tot_cost = sum(r.get('monthly_cost', 0.0) for r in rows)

    sheet.write('A4', 'TOTAL EMPLOYEES / إجمالي الموظفين', kpi_title_fmt)
    sheet.write('A5', f'{tot_emp} Employees', kpi_value_fmt)

    sheet.write('B4', 'TOTAL ATTENDANCE DAYS / إجمالي أيام الدوام', kpi_title_fmt)
    sheet.write('B5', f'{tot_days:,.2f} Days', kpi_value_fmt)

    sheet.write('C4', 'TOTAL ATTENDANCE HOURS / إجمالي ساعات الدوام', kpi_title_fmt)
    sheet.write('C5', f'{tot_hours:,.2f} Hours', kpi_value_fmt)

    sheet.write('D4', 'TOTAL COMPANY COST / إجمالي تكلفة الشركة', kpi_title_fmt)
    sheet.write('D5', tot_cost, kpi_cost_fmt)

    sheet.set_row(3, 20)
    sheet.set_row(4, 26)

    # Table Header (Row 7)
    header_row = 6
    sheet.set_row(header_row, 45)
    for col_idx, (_, label, width, _) in enumerate(COLUMNS):
        sheet.set_column(col_idx, col_idx, width)
        sheet.write_string(header_row, col_idx, label, header_fmt)

    # Data Rows
    first_data_row = header_row + 1
    for r_idx, row_data in enumerate(rows, first_data_row):
        sheet.set_row(r_idx, 28)
        for c_idx, (key, _, _, kind) in enumerate(COLUMNS):
            val = row_data.get(key)
            if val is None or val == '':
                sheet.write_blank(r_idx, c_idx, None, text_fmt if kind == 'text' else curr_fmt)
            elif kind == 'text':
                sheet.write_string(r_idx, c_idx, str(val), text_center_fmt if c_idx in (0, 5, 6, 15) else text_fmt)
            elif kind == 'number':
                sheet.write_number(r_idx, c_idx, float(val), num_fmt)
            elif kind == 'currency':
                sheet.write_number(r_idx, c_idx, float(val), curr_fmt)
            elif kind == 'cost':
                sheet.write_number(r_idx, c_idx, float(val), cost_fmt)

    last_data_row = first_data_row + len(rows) - 1

    # Autofilter & Panes
    if rows:
        sheet.autofilter(header_row, 0, last_data_row, len(COLUMNS) - 1)
        sheet.freeze_panes(first_data_row, 2)

    # Totals Row
    totals_row = last_data_row + 1 if rows else first_data_row
    sheet.set_row(totals_row, 30)
    sheet.merge_range(totals_row, 0, totals_row, 6, 'TOTAL / الإجمالي العام', total_label_fmt)

    for c_idx, (key, _, _, kind) in enumerate(COLUMNS):
        if c_idx < 7:
            continue
        if kind in ('number', 'currency', 'cost'):
            col_letter = xlsxwriter.utility.xl_col_to_name(c_idx)
            if rows:
                formula = f'=SUBTOTAL(109,{col_letter}{first_data_row + 1}:{col_letter}{last_data_row + 1})'
                val_sum = sum(row.get(key, 0.0) or 0.0 for row in rows)
                sheet.write_formula(totals_row, c_idx, formula, total_fmt, val_sum)
            else:
                sheet.write_number(totals_row, c_idx, 0.0, total_fmt)
        else:
            sheet.write_blank(totals_row, c_idx, None, total_fmt)

    sheet.print_area(0, 0, totals_row, len(COLUMNS) - 1)
    sheet.set_footer('&LEmployees Cost Center&CPage &P of &N')
    book.close()
    return buffer.getvalue()
