from . import pfr_utils
from . import res_company
from . import hr_work_entry_type
from . import hr_employee
from . import hr_attendance
from . import pfr_absent_engine
from . import pfr_day_ledger
from . import pfr_settlement
from . import hr_payslip
from . import hr_payslip_sync
from . import hr_payslip_termination
from . import hr_payroll_structure
