# -*- coding: utf-8 -*-
{
    "name": "Scheduled Orders - طلبيات تواصي",
    "summary": "إدارة طلبيات التواصي والاستلام والتوصيل وتأجيل حركات المخزون والامتثال لضريبة المبيعات جوفوتارا",
    "version": "19.0.1.0.1",
    "category": "Point of Sale",
    "author": "Anabtawi Group / Antigravity",
    "license": "LGPL-3",
    "depends": [
        "point_of_sale",
        "stock",
        "account",
        "contacts",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/account_data.xml",
        "data/product_data.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/res_partner_views.xml",
        "views/stock_picking_views.xml",
        "report/report_stock_picking_templates.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "pos_scheduled_orders/static/src/app/patches/order_model_patch.js",
            "pos_scheduled_orders/static/src/app/fulfillment_modal/fulfillment_modal.js",
            "pos_scheduled_orders/static/src/app/fulfillment_modal/fulfillment_modal.xml",
            "pos_scheduled_orders/static/src/app/catering_modal/catering_modal.js",
            "pos_scheduled_orders/static/src/app/catering_modal/catering_modal.xml",
            "pos_scheduled_orders/static/src/app/complete_schedule_modal/complete_schedule_modal.xml",
            "pos_scheduled_orders/static/src/app/control_buttons/fulfillment_button.js",
            "pos_scheduled_orders/static/src/app/control_buttons/fulfillment_button.xml",
            "pos_scheduled_orders/static/src/app/control_buttons/catering_button.js",
            "pos_scheduled_orders/static/src/app/control_buttons/catering_button.xml",
            "pos_scheduled_orders/static/src/app/control_buttons/complete_schedule_button.js",
            "pos_scheduled_orders/static/src/app/control_buttons/complete_schedule_button.xml",
            "pos_scheduled_orders/static/src/app/patches/payment_screen_patch.js",
            "pos_scheduled_orders/static/src/app/patches/order_receipt_patch.js",
            "pos_scheduled_orders/static/src/app/patches/order_receipt_patch.xml",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
