# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
from odoo.exceptions import UserError
from odoo.tools.float_utils import float_compare


class StockPickingType(models.Model):
    _inherit = "stock.picking.type"

    block_negative_stock = fields.Boolean(
        string="Block Negative Stock (Outgoing)",
        help="If enabled, validating an outgoing/internal transfer will be blocked when it would create negative stock. "
             "This check is procurement-safe (it does NOT block moves generated by Purchase, Manufacturing, or "
             "procurement/replenishment).",
        default=False,
    )


class StockPicking(models.Model):
    _inherit = "stock.picking"

    def _nsb_move_is_procurement_safe(self, move):
        """Return True if this move should NOT be blocked because it is part of procurement."""
        # Purchase receipts / dropship / etc.
        if getattr(move, "purchase_line_id", False):
            return True
        # Manufacturing finished / consumption moves
        if getattr(move, "production_id", False):
            return True
        if getattr(move, "raw_material_production_id", False):
            return True
        # Procurement group: MTO / replenishment / rules
        if getattr(move, "group_id", False):
            return True
        return False

    def _nsb_check_negative_stock(self):
        Quant = self.env["stock.quant"]
        for picking in self:
            pt = picking.picking_type_id
            if not pt or not pt.block_negative_stock:
                continue

            # Only check when goods are leaving an internal location (delivery/internal transfer).
            # Receipts (incoming) should never be blocked by this rule.
            for move in picking.move_ids:
                if move.state in ("cancel", "done"):
                    continue
                if self._nsb_move_is_procurement_safe(move):
                    continue

                # Only outgoing from internal source locations
                if move.location_id.usage != "internal":
                    continue

                # Determine quantity to validate (prefer qty_done; fallback to planned).
                qty = move.quantity_done if move.quantity_done else move.product_uom_qty
                if not qty:
                    continue

                # Convert to product's UoM
                qty_product_uom = move.product_uom._compute_quantity(qty, move.product_id.uom_id)

                # Available in the source location (strict=True respects location and owner/package/lot if provided)
                # For standard pickings, checking at move level is typically sufficient and keeps it fast.
                available = Quant._get_available_quantity(
                    move.product_id,
                    move.location_id,
                    lot_id=False,
                    package_id=False,
                    owner_id=False,
                    strict=True,
                )

                # If validating would make it negative, block
                if float_compare(available, qty_product_uom, precision_rounding=move.product_id.uom_id.rounding) < 0:
                    raise UserError(_(
                        "Negative stock is not allowed for this operation type.\n\n"
                        "Operation: %(op)s\n"
                        "Product: %(product)s\n"
                        "Source Location: %(loc)s\n"
                        "Available: %(avail)s\n"
                        "To Transfer: %(qty)s\n\n"
                        "Note: Procurement-generated moves (Purchase/Manufacturing/Replenishment) are not blocked."
                    ) % {
                        "op": pt.display_name,
                        "product": move.product_id.display_name,
                        "loc": move.location_id.display_name,
                        "avail": available,
                        "qty": qty_product_uom,
                    })

    def button_validate(self):
        # Check BEFORE standard validation, so no partial processing occurs
        self._nsb_check_negative_stock()
        return super().button_validate()
