import io
from datetime import datetime

from odoo import _, fields, models, exceptions
from odoo.tools.misc import format_date


class HrPayslipRun(models.Model):
    _inherit = "hr.payslip.run"

    def action_export_payrun_excel(self):
        self.ensure_one()
        url = f"/anabtawi_payroll/payrun/xlsx?payrun_id={self.id}"
        
        ctx = self.env.context
        if ctx.get("active_model") == "hr.payslip" and ctx.get("active_ids"):
            selected_ids = ",".join(str(i) for i in ctx.get("active_ids"))
            url += f"&payslip_ids={selected_ids}"

        return {
            "name": "PayRun Audit",
            "type": "ir.actions.act_url",
            "url": url,
            "target": "self",
        }

    def _generate_payrun_xlsx(self, quick_audit=False, payslip_ids=None):
        self.ensure_one()
        import xlsxwriter  # pylint: disable=import-outside-toplevel

        workbook_buffer = io.BytesIO()
        workbook = xlsxwriter.Workbook(workbook_buffer, {"in_memory": True})

        # Styling Definitions
        title_fmt = workbook.add_format(
            {"bold": True, "font_size": 15, "font_color": "#1F497D"}
        )
        meta_label_fmt = workbook.add_format(
            {"bold": True, "bg_color": "#F2F4F8", "border": 1, "font_size": 10}
        )
        meta_val_fmt = workbook.add_format(
            {"border": 1, "font_size": 10, "align": "left"}
        )
        
        card_header_fmt = workbook.add_format(
            {"bold": True, "bg_color": "#D9E1F2", "border": 1, "align": "center", "font_size": 10}
        )
        card_val_fmt = workbook.add_format(
            {"bold": True, "border": 1, "align": "center", "font_size": 11, "num_format": "#,##0.00"}
        )

        header_fmt = workbook.add_format(
            {
                "bold": True,
                "font_color": "#FFFFFF",
                "bg_color": "#1F497D",
                "border": 1,
                "align": "center",
                "valign": "vcenter",
                "text_wrap": True,
                "font_size": 10,
            }
        )
        
        text_left_fmt = workbook.add_format({"border": 1, "align": "left", "font_size": 10})
        text_center_fmt = workbook.add_format({"border": 1, "align": "center", "font_size": 10})
        number_fmt = workbook.add_format({"border": 1, "align": "right", "num_format": "#,##0.00", "font_size": 10})
        int_fmt = workbook.add_format({"border": 1, "align": "right", "num_format": "#,##0", "font_size": 10})

        net_negative_fmt = workbook.add_format(
            {"border": 1, "align": "right", "num_format": "#,##0.00", "font_size": 10, "bg_color": "#FCE4D6", "font_color": "#C00000", "bold": True}
        )

        total_label_fmt = workbook.add_format(
            {"bold": True, "border": 1, "bg_color": "#E9ECEF", "align": "left", "font_size": 10}
        )
        total_num_fmt = workbook.add_format(
            {"bold": True, "border": 1, "bg_color": "#E9ECEF", "align": "right", "num_format": "#,##0.00", "font_size": 10}
        )
        total_int_fmt = workbook.add_format(
            {"bold": True, "border": 1, "bg_color": "#E9ECEF", "align": "right", "num_format": "#,##0", "font_size": 10}
        )

        audit_ok_fmt = workbook.add_format({"border": 1, "align": "center", "bg_color": "#E2EFDA", "font_color": "#375623", "bold": True})
        audit_warn_fmt = workbook.add_format({"border": 1, "align": "center", "bg_color": "#FFF2CC", "font_color": "#7F6000", "bold": True})
        audit_err_fmt = workbook.add_format({"border": 1, "align": "center", "bg_color": "#FCE4D6", "font_color": "#C00000", "bold": True})

        # Filter payslips to only include selected employee payslips if specified
        if payslip_ids:
            payslips = self.slip_ids.filtered(lambda p: p.id in payslip_ids)
        else:
            payslips = self.slip_ids

        # -------------------------------------------------------------
        # SHEET 1: PayRun Audit
        # -------------------------------------------------------------
        sheet1_name = "PayRun Audit"

        sheet1 = workbook.add_worksheet(sheet1_name)
        sheet1.set_landscape()

        # Write Metadata (Rows 0-5)
        sheet1.write(0, 0, f"Odoo Payroll Report - PayRun Audit ({self.name or _('Pay Run')})", title_fmt)

        meta_items = [
            (_("Pay Run ID / Name"), self.name or "N/A"),
            (_("Period From"), format_date(self.env, self.date_start) if self.date_start else "N/A"),
            (_("Period To"), format_date(self.env, self.date_end) if self.date_end else "N/A"),
            (_("Generated By"), self.env.user.name or "System"),
            (_("Generated On"), fields.Datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
            (_("Source System"), "Odoo 19 Payroll"),
            (_("Template Version"), "v1.4 (Exact Salary Rules Integration)"),
        ]

        row = 2
        for i, (label, val) in enumerate(meta_items):
            c_idx = (i % 2) * 3
            r_idx = row + (i // 2)
            sheet1.write(r_idx, c_idx, label, meta_label_fmt)
            sheet1.write(r_idx, c_idx + 1, val, meta_val_fmt)

        row = 7
        # Write KPI / Summary block directly from computed payslip wages
        total_gross_val = sum(payslips.mapped("gross_wage") if "gross_wage" in payslips._fields else [
            sum(p.line_ids.filtered(lambda l: l.code == "GROSS" or l.category_id.code in ("GROSS", "Gross")).mapped("total")) for p in payslips
        ])
        total_net_val = sum(payslips.mapped("net_wage") if "net_wage" in payslips._fields else [
            sum(p.line_ids.filtered(lambda l: l.code == "NET" or l.category_id.code in ("NET", "Net")).mapped("total")) for p in payslips
        ])
        
        # Calculate summary metrics directly from exact system rule codes
        all_lines = payslips.mapped("line_ids")
        tax_lines = all_lines.filtered(lambda l: l.code in ("INCOME_TAX", "TAX", "IT") or "ضريبة" in l.name)
        ssc_comp_lines = all_lines.filtered(lambda l: l.code in ("SSC", "SSCC", "SSC_COMP", "SOC_SEC_COMP") or ("ضمان" in l.name and "شركة" in l.name))
        ssc_emp_lines = all_lines.filtered(lambda l: l.code in ("SSE", "SSCE", "SSC_EMP", "SOC_SEC_EMP") or ("ضمان" in l.name and "موظف" in l.name))
        loan_lines = all_lines.filtered(lambda l: l.code in ("COMPANY", "COMLON", "adv_pay", "adve", "LOAN", "LOANS", "ADVANCE") or "سلفة" in l.name or "سلفيات" in l.name)
        
        total_tax = sum(tax_lines.mapped("total"))
        total_ssc = sum(ssc_comp_lines.mapped("total")) + sum(ssc_emp_lines.mapped("total"))
        total_loan = sum(loan_lines.mapped("total"))
        emp_count = len(payslips)
        avg_net = (total_net_val / emp_count) if emp_count > 0 else 0.0

        sheet1.write(row, 0, _("Total Gross (JOD)"), card_header_fmt)
        sheet1.write(row, 1, _("Total Tax (JOD)"), card_header_fmt)
        sheet1.write(row, 2, _("Total SSC (JOD)"), card_header_fmt)
        sheet1.write(row, 3, _("Total Loans (JOD)"), card_header_fmt)
        sheet1.write(row, 4, _("Total Net (JOD)"), card_header_fmt)
        sheet1.write(row, 5, _("Avg Net / Emp (JOD)"), card_header_fmt)

        sheet1.write_number(row + 1, 0, total_gross_val, card_val_fmt)
        sheet1.write_number(row + 1, 1, total_tax, card_val_fmt)
        sheet1.write_number(row + 1, 2, total_ssc, card_val_fmt)
        sheet1.write_number(row + 1, 3, total_loan, card_val_fmt)
        sheet1.write_number(row + 1, 4, total_net_val, card_val_fmt)
        sheet1.write_number(row + 1, 5, avg_net, card_val_fmt)

        row += 3

        # -------------------------------------------------------------
        # Dynamic Columns Setup for Salary Inputs
        # -------------------------------------------------------------
        base_cols_before = [
            (_("Employee ID"), 14),
            (_("Employee Name"), 28),
            (_("Department"), 22),
            (_("Job Title / Position"), 22),
            (_("Internal Code"), 16),
            (_("Period From"), 14),
            (_("Period To"), 14),
            (_("Basic Salary"), 16),
            (_("Remaining Leaves Comp"), 20),
            (_("Gross Attendance / OT"), 20),
            (_("Other Earnings"), 16),
            (_("Gross Salary (before tax)"), 22),
            (_("Income Tax"), 16),
            (_("SSC Company Contrib"), 20),
            (_("SSC Employee Contrib"), 20),
            (_("Company Loan"), 16),
            (_("Other Deductions"), 18),
        ]

        # Discover all unique Salary Input Types present across selected payslips
        input_types = payslips.mapped("input_line_ids.input_type_id").sorted(key=lambda t: t.name or "")
        
        input_cols = []
        if input_types:
            for itype in input_types:
                t_name = itype.name or _("Salary Input")
                col_name = f"Input: {t_name}" if not t_name.lower().startswith("input") else t_name
                input_cols.append((col_name, max(18, len(col_name) + 4), itype))
        else:
            input_cols.append((_("Salary Inputs"), 18, None))

        base_cols_after = [
            (_("Net Salary"), 18),
            (_("Attendance Days"), 16),
            (_("Worked Hours"), 15),
            (_("Overtime Hours"), 15),
            (_("Note / Description"), 30),
        ]

        all_columns = base_cols_before + [(name, width) for name, width, _ in input_cols] + base_cols_after

        for col_idx, (col_name, width) in enumerate(all_columns):
            sheet1.set_column(col_idx, col_idx, width)
            sheet1.write(row, col_idx, col_name, header_fmt)

        table_start_row = row + 1
        data_row = table_start_row

        audit_entries = []

        if not payslips:
            audit_entries.append({
                "emp_id": "N/A",
                "emp_name": "N/A",
                "dept": "N/A",
                "status": "WARNING",
                "remarks": _("No employees included in this selection."),
            })
        else:
            for payslip in payslips:
                emp = payslip.employee_id
                issues = []
                
                emp_id_val = (
                    getattr(emp, "employee_number", False)
                    or getattr(emp, "registration_number", False)
                    or getattr(emp, "barcode", False)
                    or (str(emp.id) if emp else "N/A")
                )
                if not emp:
                    issues.append(_("Missing Employee record"))
                elif not getattr(emp, "employee_number", False):
                    issues.append(_("Missing Employee Number"))

                emp_name_val = emp.legal_name or emp.name if emp else "N/A"
                dept_val = emp.department_id.name if emp and emp.department_id else "N/A"
                if emp and not emp.department_id:
                    issues.append(_("Missing Department"))

                job_val = emp.job_id.name if emp and emp.job_id else "N/A"
                code_val = emp_id_val

                period_from_val = format_date(self.env, payslip.date_from or self.date_start)
                period_to_val = format_date(self.env, payslip.date_to or self.date_end)

                # Line helper strictly matching exact system codes from Odoo salary rules
                lines = payslip.line_ids

                # 1. Basic Salary (Rule codes: BASIC, SALARY, FULL_WAGE or category BASIC)
                basic_sal = sum(lines.filtered(lambda l: l.code in ("BASIC", "SALARY", "FULL_WAGE") or (l.category_id and l.category_id.code in ("BASIC", "Basic")) or (l.category_id and l.category_id.name in ("BASIC", "Basic", "Basic Salary"))).mapped("total"))

                # 2. Remaining Leaves Compensation (Rule codes: vacation_leave, remain_lev, REM_LEAVE, LEAVE_COMP, ANNUAL_LEAVE)
                rem_leave = sum(lines.filtered(lambda l: l.code in ("vacation_leave", "remain_lev", "REM_LEAVE", "LEAVE_COMP", "ANNUAL_LEAVE")).mapped("total"))
                
                # 3. Gross Attendance / Overtime (Rule codes: OT_NET, ETH_NET, RD-S, OVERTIME, GROSS_ATT, OT_COMP, EXTRA_HOURS)
                gross_att_ot = sum(lines.filtered(lambda l: l.code in ("OT_NET", "ETH_NET", "RD-S", "OVERTIME", "GROSS_ATT", "OT_COMP", "EXTRA_HOURS")).mapped("total"))

                # 4. Other Earnings (All Allowance category lines: HOU_ALLOW, TRAALLOW, month_alw, expatriation_alw, diff, car_alw, eos_benefit, sales, etc.)
                all_alw = sum(lines.filtered(lambda l: (l.category_id and l.category_id.code in ("ALW", "Allowance", "ALLOWANCE")) or (l.category_id and "allowance" in (l.category_id.name or "").lower())).mapped("total"))
                other_earnings = max(0.0, all_alw - basic_sal - rem_leave - gross_att_ot)

                # 5. Gross Salary
                gross_sal = payslip.gross_wage if hasattr(payslip, "gross_wage") and payslip.gross_wage else sum(lines.filtered(lambda l: l.code == "GROSS" or (l.category_id and l.category_id.code in ("GROSS", "Gross"))).mapped("total"))
                if not gross_sal:
                    gross_sal = basic_sal + rem_leave + gross_att_ot + other_earnings

                # 6. Income Tax (Rule code: INCOME_TAX)
                tax_val = sum(lines.filtered(lambda l: l.code in ("INCOME_TAX", "TAX", "IT") or "ضريبة" in l.name).mapped("total"))
                
                # 7. SSC Company (Rule code: SSC)
                sscc_val = sum(lines.filtered(lambda l: l.code in ("SSC", "SSCC", "SSC_COMP", "SOC_SEC_COMP") or ("ضمان" in l.name and "شركة" in l.name)).mapped("total"))
                
                # 8. SSC Employee (Rule code: SSE)
                ssce_val = sum(lines.filtered(lambda l: l.code in ("SSE", "SSCE", "SSC_EMP", "SOC_SEC_EMP") or ("ضمان" in l.name and "موظف" in l.name)).mapped("total"))
                
                # 9. Company Loan (Rule codes: COMPANY, COMLON, adv_pay, adve)
                loan_val = sum(lines.filtered(lambda l: l.code in ("COMPANY", "COMLON", "adv_pay", "adve", "LOAN", "LOANS", "ADVANCE") or "سلفة" in l.name or "سلفيات" in l.name).mapped("total"))

                # 10. Salary Input Values rendered in dedicated input columns
                rendered_inputs_total = 0.0
                input_vals = []
                for _name, _width, itype in input_cols:
                    if itype:
                        matching_inputs = payslip.input_line_ids.filtered(lambda l: l.input_type_id == itype)
                        in_val = sum((l.amount if l.amount != 0.0 else l.quantity) or 0.0 for l in matching_inputs)
                    else:
                        in_val = sum((l.amount if l.amount != 0.0 else l.quantity) or 0.0 for l in payslip.input_line_ids)
                    input_vals.append(in_val)
                    rendered_inputs_total += in_val

                # 11. Other Deductions (Deduction category lines: HIE, OUTCON, penalties, Court, sickness_ded, cash_deficit, truncation, CLEDGER minus tax, ssce, loan, and input deductions)
                all_ded = sum(lines.filtered(lambda l: (l.category_id and l.category_id.code in ("DED", "Deduction", "DEDUCTION", "Social Security Deduction")) or (l.category_id and "deduction" in (l.category_id.name or "").lower())).mapped("total"))
                other_ded = max(0.0, all_ded - tax_val - ssce_val - loan_val - rendered_inputs_total)

                # 12. Net Salary (Rule code: NET)
                net_sal = payslip.net_wage if hasattr(payslip, "net_wage") and payslip.net_wage else sum(lines.filtered(lambda l: l.code == "NET" or (l.category_id and l.category_id.code in ("NET", "Net"))).mapped("total"))

                if net_sal < 0:
                    issues.append(_("Negative Net Salary (%.2f JOD)") % net_sal)

                # Attendance metrics strictly from payslip.worked_days_line_ids
                worked_days = payslip.worked_days_line_ids
                att_days = sum(worked_days.mapped("number_of_days"))
                worked_hrs = sum(worked_days.mapped("number_of_hours"))
                ot_hrs = sum(worked_days.filtered(lambda wd: "overtime" in (wd.code or "").lower() or "ot" in (wd.code or "").lower()).mapped("number_of_hours"))

                # Gather notes strictly from payslip and salary input lines
                input_notes = []
                for input_line in payslip.input_line_ids:
                    note_txt = input_line.name or getattr(input_line, "note", False)
                    if note_txt:
                        t_label = input_line.input_type_id.name or _("Input")
                        input_notes.append(f"[{t_label}: {note_txt}]")

                base_note = payslip.note or payslip.name or ""
                if input_notes:
                    note_val = f"{base_note} {' '.join(input_notes)}".strip()
                else:
                    note_val = base_note

                # Write Base Before Columns (0..16)
                sheet1.write(data_row, 0, emp_id_val, text_center_fmt)
                sheet1.write(data_row, 1, emp_name_val, text_left_fmt)
                sheet1.write(data_row, 2, dept_val, text_left_fmt)
                sheet1.write(data_row, 3, job_val, text_left_fmt)
                sheet1.write(data_row, 4, code_val, text_center_fmt)
                sheet1.write(data_row, 5, period_from_val, text_center_fmt)
                sheet1.write(data_row, 6, period_to_val, text_center_fmt)
                
                sheet1.write_number(data_row, 7, basic_sal, number_fmt)
                sheet1.write_number(data_row, 8, rem_leave, number_fmt)
                sheet1.write_number(data_row, 9, gross_att_ot, number_fmt)
                sheet1.write_number(data_row, 10, other_earnings, number_fmt)
                sheet1.write_number(data_row, 11, gross_sal, number_fmt)
                sheet1.write_number(data_row, 12, tax_val, number_fmt)
                sheet1.write_number(data_row, 13, sscc_val, number_fmt)
                sheet1.write_number(data_row, 14, ssce_val, number_fmt)
                sheet1.write_number(data_row, 15, loan_val, number_fmt)
                sheet1.write_number(data_row, 16, other_ded, number_fmt)

                # Write Dynamic Salary Input Columns
                col_curr = len(base_cols_before)
                for in_val in input_vals:
                    sheet1.write_number(data_row, col_curr, in_val, number_fmt)
                    col_curr += 1

                # Write Base After Columns
                net_style = net_negative_fmt if net_sal < 0 else number_fmt
                sheet1.write_number(data_row, col_curr, net_sal, net_style)
                sheet1.write_number(data_row, col_curr + 1, att_days, int_fmt)
                sheet1.write_number(data_row, col_curr + 2, worked_hrs, number_fmt)
                sheet1.write_number(data_row, col_curr + 3, ot_hrs, number_fmt)
                sheet1.write(data_row, col_curr + 4, note_val, text_left_fmt)

                if not lines and payslip.state != "cancel":
                    issues.append(_("Payslip lines not computed"))

                status = "ERROR" if any("Negative" in i or "not computed" in i for i in issues) else ("WARNING" if issues else "OK")
                remarks = ", ".join(issues) if issues else _("Computation verified cleanly")

                audit_entries.append({
                    "emp_id": emp_id_val,
                    "emp_name": emp_name_val,
                    "dept": dept_val,
                    "status": status,
                    "remarks": remarks,
                })

                data_row += 1

        # Write Total Row at bottom
        sheet1.write(data_row, 0, _("Total"), total_label_fmt)
        for c in range(1, 7):
            sheet1.write(data_row, c, "", total_label_fmt)

        total_num_cols = len(base_cols_before) + len(input_cols) + 4
        for col_idx in range(7, total_num_cols):
            col_letter = xlsxwriter.utility.xl_col_to_name(col_idx)
            formula = f"=SUM({col_letter}{table_start_row + 1}:{col_letter}{data_row})"
            
            att_days_col_idx = len(base_cols_before) + len(input_cols) + 1
            fmt = total_int_fmt if col_idx == att_days_col_idx else total_num_fmt
            sheet1.write_formula(data_row, col_idx, formula, fmt)

        sheet1.write(data_row, total_num_cols, "", total_label_fmt)

        # -------------------------------------------------------------
        # SHEET 2: Audit
        # -------------------------------------------------------------
        sheet2 = workbook.add_worksheet("Audit")
        sheet2.set_column(0, 0, 14)
        sheet2.set_column(1, 1, 28)
        sheet2.set_column(2, 2, 22)
        sheet2.set_column(3, 3, 16)
        sheet2.set_column(4, 4, 45)

        sheet2.write(0, 0, _("Pay Run Audit Trail & Exception Log"), title_fmt)
        sheet2.write(1, 0, _("Pay Run: %s") % (self.name or ""), meta_val_fmt)

        audit_headers = [
            _("Employee ID"),
            _("Employee Name"),
            _("Department"),
            _("Audit Status"),
            _("Issue / Remarks"),
        ]
        for c_idx, h_text in enumerate(audit_headers):
            sheet2.write(3, c_idx, h_text, header_fmt)

        a_row = 4
        for entry in audit_entries:
            st = entry["status"]
            st_fmt = audit_ok_fmt if st == "OK" else (audit_warn_fmt if st == "WARNING" else audit_err_fmt)

            sheet2.write(a_row, 0, entry["emp_id"], text_center_fmt)
            sheet2.write(a_row, 1, entry["emp_name"], text_left_fmt)
            sheet2.write(a_row, 2, entry["dept"], text_left_fmt)
            sheet2.write(a_row, 3, st, st_fmt)
            sheet2.write(a_row, 4, entry["remarks"], text_left_fmt)
            a_row += 1

        sheet2.write(a_row, 0, _("Summary Total"), total_label_fmt)
        sheet2.write(a_row, 1, _("Total Audited Records: %d") % len(audit_entries), total_label_fmt)
        sheet2.write(a_row, 2, "", total_label_fmt)
        sheet2.write(a_row, 3, "", total_label_fmt)
        sheet2.write(a_row, 4, "", total_label_fmt)

        workbook.close()
        return workbook_buffer.getvalue()
