{
    'name': 'Custom Cake Builder | قوالب جاتو مخصصة',
    'version': '19.0.1.0.0',
    'category': 'Point of Sale',
    'summary': 'POS popup → cashier picks size + ingredients → selling price calculated → cart updated → MO auto-created → email to manufacturing',
    'author': 'Custom',
    'depends': ['point_of_sale', 'mrp', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cake_ingredient_data.xml',
        'views/cake_ingredient_views.xml',
        'views/cake_extra_feature_views.xml',
        'views/cake_order_views.xml',
        'views/cake_config_views.xml',
        'report/cake_order_report.xml',
        'report/cake_order_report_template.xml',
        'wizard/send_cake_email_views.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'cake_pos/static/src/js/cake_popup.js',
            'cake_pos/static/src/js/cake_button_patch.js',
            'cake_pos/static/src/xml/cake_popup.xml',
            'cake_pos/static/src/xml/cake_button_patch.xml',
            'cake_pos/static/src/css/cake_popup.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
