# -*- coding: utf-8 -*-
{'name': 'Anabtawi Invest Portfolio',
 'version': '19.0.1.0.0',
 'summary': 'An elegant Arabic corporate portfolio for Anabtawi Invest',
 'author': 'Anabtawi Invest',
 'category': 'Website',
 'license': 'LGPL-3',
 'depends': ['website'],
 'data': ['data/website.xml',
          'views/layout.xml',
          'views/snippets/snippets.xml',
          'views/home.xml',
          'data/pages/portfolio.xml',
          'data/menus.xml'],
 'assets': {'web.assets_frontend': ['Anabtawi_invest_web_new_2/static/src/scss/primary_variables.scss',
                                    'Anabtawi_invest_web_new_2/static/src/scss/website_style.scss',
                                    'Anabtawi_invest_web_new_2/static/src/js/portfolio_core.js',
                                    'Anabtawi_invest_web_new_2/static/src/js/portfolio.js']},
 'images': ['static/description/icon.png'],
 'installable': True,
 'application': True}
