"""Excel presentation only; business values come from the installed payroll engine."""
import io
from datetime import datetime, time

import xlsxwriter


# Key, label, width, kind. Deductions are signed negative, balances keep their sign.
COLUMNS = [
    ('employee_code', 'Employee ID', 17, 'text'),
    ('employee', 'Employee Name', 32, 'text'),
    ('department', 'Department', 23, 'text'),
    ('job', 'Job Position', 23, 'text'),
    ('payslip', 'Payslip', 30, 'text'),
    ('payrun', 'Pay Run', 25, 'text'),
    ('date_from', 'Period From', 14, 'date'),
    ('date_to', 'Period To', 14, 'date'),
    ('state', 'Payslip Status', 18, 'text'),
    ('reconciliation', 'Reconciliation Status', 28, 'text'),
    ('overtime', 'Monthly Overtime Earned (hrs)', 21, 'signed'),
    ('lateness', 'Monthly Lateness / Undertime (hrs)', 23, 'signed'),
    ('opening', 'Previous Extra Hours (hrs)', 21, 'signed'),
    ('available', 'Total Extra Hours Available (hrs)', 23, 'signed'),
    ('variance', 'Monthly OT minus Lateness (hrs)', 23, 'signed'),
    ('extra_cut', 'Step 1: Deducted from Extra Hours (hrs)', 25, 'signed'),
    ('annual_cut', 'Step 2: Deducted from Annual Leave (hrs)', 25, 'signed'),
    ('cash_hours', 'Step 3: Salary Deduction Hours (hrs)', 25, 'signed'),
    ('remaining', 'Remaining Extra Hours Balance (hrs)', 25, 'signed'),
    ('cash_amount', 'Salary Deduction Amount', 23, 'signed'),
    ('net', 'Net Salary', 20, 'number'),
    ('currency', 'Currency', 12, 'text'),
    ('check', 'Settlement Difference (hrs)', 23, 'check'),
    ('notes', 'Notes', 55, 'text'),
]


def build_xlsx(rows, metadata):
    buffer = io.BytesIO()
    book = xlsxwriter.Workbook(buffer, {'in_memory': True, 'strings_to_formulas': False,
                                      'strings_to_urls': False})
    sheet = book.add_worksheet('Reconciled Report')
    sheet.hide_gridlines(2)
    sheet.set_landscape()
    sheet.set_paper(8)
    sheet.fit_to_pages(1, 0)
    sheet.set_zoom(85)
    title = book.add_format({'bold': True, 'font_size': 19, 'font_color': '#17365D'})
    info = book.add_format({'font_size': 11, 'font_color': '#46556A', 'text_wrap': True})
    header = book.add_format({'bold': True, 'bg_color': '#17365D', 'font_color': '#FFFFFF',
                              'text_wrap': True, 'valign': 'vcenter', 'border': 1})
    base = {'font_name': 'Calibri', 'font_size': 11, 'border': 1, 'border_color': '#DCE3EB',
            'valign': 'vcenter'}
    text_fmt = book.add_format(dict(base, text_wrap=True))
    number = book.add_format(dict(base, num_format='0.00;[Red]-0.00;"—"'))
    date_fmt = book.add_format(dict(base, num_format='yyyy-mm-dd'))
    green = book.add_format({'bg_color': '#E2F0D9', 'font_color': '#176B36'})
    red = book.add_format({'bg_color': '#FCE4D6', 'font_color': '#B91C1C'})
    total = book.add_format(dict(base, bold=True, bg_color='#E8EEF5',
                                num_format='0.00;[Red]-0.00;"—"'))
    sheet.merge_range('A1:H2', 'PAYROLL | RECONCILED REPORT', title)
    sheet.merge_range('A3:H3', metadata['company'] + ' | ' + metadata['period'], info)
    sheet.merge_range('A4:H4', 'Generated by: ' + metadata['user'] + ' | ' + metadata['generated'], info)
    sheet.merge_range('A5:H5', 'Green = extra hours / positive balance. Red = lateness / deductions / negative balance.', info)
    sheet.merge_range('A6:H6', 'Hours are decimal: 1.50 = 01:30. Monthly variance excludes previous extra hours.', info)
    sheet.merge_range('A7:H7', 'Computed does not mean approved. Leave settlements follow the existing payslip confirmation workflow.', info)
    sheet.merge_range('A8:H8', 'Salary deduction is the computed DED_UNDERTIME rule, included in Net Salary; do not subtract it again.', info)
    for r in range(2, 8):
        sheet.set_row(r, 24)
    header_row = 9
    sheet.set_row(header_row, 60)
    for col, (_, label, width, _) in enumerate(COLUMNS):
        sheet.set_column(col, col, width)
        sheet.write_string(header_row, col, label, header)
    first = header_row + 1
    for row_index, values in enumerate(rows, first):
        sheet.set_row(row_index, 43)
        for col, (key, _, _, kind) in enumerate(COLUMNS):
            value = values.get(key)
            if value is None:
                sheet.write_blank(row_index, col, None, number if kind != 'text' else text_fmt)
            elif kind == 'date':
                sheet.write_datetime(row_index, col, datetime.combine(value, time.min), date_fmt)
            elif kind in ('signed', 'number', 'check'):
                sheet.write_number(row_index, col, value, number)
            else:
                sheet.write_string(row_index, col, str(value), text_fmt)
    last = first + len(rows) - 1
    sheet.autofilter(header_row, 0, last, len(COLUMNS) - 1)
    sheet.freeze_panes(first, 2)
    sheet.repeat_rows(0, header_row)
    sheet.set_footer('&LReconciled Report&CPage &P of &N')
    for col, (_, _, _, kind) in enumerate(COLUMNS):
        if kind == 'signed':
            sheet.conditional_format(first, col, last, col, {'type': 'cell', 'criteria': '>', 'value': 0, 'format': green})
        if kind in ('signed', 'number'):
            sheet.conditional_format(first, col, last, col, {'type': 'cell', 'criteria': '<', 'value': 0, 'format': red})
        if kind == 'check':
            sheet.conditional_format(first, col, last, col, {'type': 'cell', 'criteria': 'not between',
                                                           'minimum': -0.02, 'maximum': 0.02, 'format': red})
    totals_row = last + 1
    sheet.write_string(totals_row, 0, 'TOTAL', total)
    for col, (key, _, _, kind) in enumerate(COLUMNS):
        if kind in ('signed', 'number', 'check'):
            values = [row[key] for row in rows if row.get(key) is not None]
            # Missing money remains missing, rather than understating the total.
            if len(values) != len(rows):
                sheet.write_string(totals_row, col, 'Incomplete', total)
            else:
                letter = xlsxwriter.utility.xl_col_to_name(col)
                sheet.write_formula(totals_row, col, f'=SUBTOTAL(109,{letter}{first+1}:{letter}{last+1})', total, sum(values))
    sheet.print_area(0, 0, totals_row, len(COLUMNS) - 1)
    book.close()
    return buffer.getvalue()
