{
    "name": "Anabtawi Direct Sales Invoice",
    "summary": "Warehouse-approved direct customer invoicing with stock traceability",
    "version": "19.0.1.0.0",
    "category": "Sales/Inventory/Accounting",
    "author": "Anabtawi Sweets",
    "website": "https://www.anabtawisweets.com",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "sale_management",
        "account",
        "stock",
        "product",
        "contacts",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/mail_activity_type.xml",
        "data/cron.xml",
        "views/direct_sales_invoice_views.xml",
        "views/account_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_warehouse_views.xml",
        "views/res_config_settings_views.xml",
        "views/wizard_views.xml",
        "views/reporting_views.xml",
        "report/warehouse_preparation_templates.xml",
        "report/warehouse_preparation_report.xml",
        "report/goods_release_templates.xml",
        "report/goods_release_report.xml",
        "report/commercial_audit_templates.xml",
        "report/commercial_audit_report.xml",
        "views/menu_views.xml",
    ],
    "assets": {},
    "application": True,
    "installable": True,
    "auto_install": False,
}
